### ISSUE TITLE
Update `before` ability once implemented by ember-cli-deploy

### ISSUE THREAD

**Issue by achambers** [ember-cli-deploy/ember-cli-deploy-revision-data#2]
Once ember-cli-deploy has the ability to specify which addons run before and after others, we can remove it from the `package.json`

**Comment by ghedamat** [comment]
@achambers I believe this one can be closed as a WONTFIX

c/d?

**Comment by achambers** [comment]
@ghedamat Are we happy with the current way plugin authors have for specifying that their plugin runs before/after another?

**Comment by ghedamat** [comment]
@achambers I think I am, at least for the plugin authors part what we have feels it can be enough

for the user side there's the pr from ef4

let me know if you agree otherwise we can leave it open and decide if we wanna target a future release or just leave it as a reminder

/cc @lukemelia

**Comment by achambers** [comment]
I'm happy with that mate.
