### ISSUE TITLE
Configuration

### ISSUE THREAD

**Issue by lcpriest** [ember-cli-deploy/ember-cli-deploy-revision-data#24]
The configuration for this goes In the ember-cli-build.js file, correct?

```
var ENV = {
    build: {},
    redis: {
      allowOverwrite: true,
      keyPrefix: 'myapp'
    },
    s3: {
      prefix: 'myapp'
    }
  };
```

What is the parent key? I imagine that "type" is too generic to be a global setting, but I can't see anywhere in this repo that says what the parent key would be.

**Comment by lcpriest** [comment]
Oh, it's "revision-data". 

Can we put that in the readme?

**Comment by lukemelia** [comment]
@lcpriest We're open to any README PRs that you think would make adoption smoother for people new to the project.
