### ISSUE TITLE
README says git-tag-commit uses most recent tag, but it doesn't work unless current commit has a tag

### ISSUE THREAD

**Issue by Gaurav0** [ember-cli-deploy/ember-cli-deploy-revision-data#27]

**Comment by Truffula** [comment]
[git-repo-info](https://github.com/rwjblue/git-repo-info) only returns info for the current build. [git-latest-tag](https://github.com/stevemao/git-latest-tag) gets the latest tag.

**Comment by jrowlingson** [comment]
There is no timestamp stored with a lightweight tag since its simply a reference. So this is more of a doc bug.

On the other hand, annotated tags do contain a timestamp so an option for this could be added to the generator.

**Comment by jrowlingson** [comment]
Related https://github.com/rwjblue/git-repo-info/issues/32
