### ISSUE TITLE
Packed annotated tag causes git-tag-commit failure

### ISSUE THREAD

**Issue by jrowlingson** [ember-cli-deploy/ember-cli-deploy-revision-data#49]
If you see an error message that looks like:

```
|  +- revision-data
|    - creating revision data using `git-tag-commit`
|    - Could not build revision with tag `null` and commit hash `8d494088`
|
+- didFail
Could not build revision with tag `null` and commit hash `8d494088`
```

It may be caused by an [undefined tag](https://github.com/ember-cli-deploy/ember-cli-deploy-revision-data/blob/f7b6d7ba76e29e3e5094a1bdf66a21b07e4d5d15/lib/data-generators/git-tag-commit.js#L18) returned from `gitRepoInfo`. 

Related: https://github.com/rwjblue/git-repo-info/issues/30

**Comment by jrowlingson** [comment]
Fix included via https://github.com/ember-cli-deploy/ember-cli-deploy-revision-data/pull/46

**Comment by ahemed-haneen** [comment]
@jrowlingson 
could you share the revision data configuration. im still getting those errors
