### ISSUE TITLE
Crashes on non-git projects

### ISSUE THREAD

**Issue by duizendnegen** [ember-cli-deploy/ember-cli-deploy-revision-data#58]
`scm` is unavailable, leading to

```
simpleGit(_this.path).log(function(err, log) {
  var info = log.latest;
```

throwing an error.
Shall we just resolve with an empty response instead in case of `!log`?

**Comment by jhliberty** [comment]
I'm experiencing this same issue even using the version pointed at master with the referenced pull request merged in.

```
var info = log.latest;
^

TypeError: Cannot read property 'latest' of null
```

**Comment by duizendnegen** [comment]
Thanks @jhliberty - proposed https://github.com/ember-cli-deploy/ember-cli-deploy-revision-data/pull/61, can you check with that fix?

**Comment by jhliberty** [comment]
I tried out the commit and it worked successfully. Thanks for the quick resolution! 

I looked around the source and saw this in index.js: 

```
  _getScmData: function() {
        var ScmDataGenerator = this.readConfig('scm');
        if (ScmDataGenerator) {
          var path = this.readConfig('distDir');
          return new ScmDataGenerator(path).generate();
        } else {
          return RSVP.resolve();
        }
      },
```

So setting `scm: false` in your deploy config for this addon would also prevent that function from even firing.

Thought that was useful as well, though using file-hash shouldn't fail on non-git systems so 👍  but someone may find this config useful.
