### ISSUE TITLE
Generate data earlier in the deployment process

### ISSUE THREAD

**Issue by marcoow** [ember-cli-deploy/ember-cli-deploy-revision-data#62]
I was trying to use the revision data during the `build` step of the deployment process and was surprised I couldn't because it is only generated in the `prepare` step. I wonder why that is as it should be possible to generate the data earlier, e.g. in `build` or even earlier in `configure` or `setup`.

I'd be happy to submit a PR, just not sure there's a good reason maybe why the data isn't (or can't be) generated earlier in the process?

**Comment by lukemelia** [comment]
Hi @marcoow, in at some cases, the revision data plugin generates data including the hash of the index.html file, which is of course the output of the build process.

The vision for how to proceed is here: https://github.com/ember-cli-deploy/ember-cli-deploy/issues/477

**Comment by marcoow** [comment]
makes sense, closing this 👍
