### ISSUE TITLE
Git working directory is not clean, commit any change before using `ember deploy`

### ISSUE THREAD

**Issue by jfrux** [ember-cli-deploy/ember-cli-deploy-revision-data#65]
Is there not a way to just tell it what I want the unique key to be instead of it tying into Git info?
I'd like to have a bit less rigid deployment strategy with the ability to deploy whether I've committed or not.

This plugin is required by another plugin I need so I can't exactly NOT use it at the moment.

Any tips?

**Comment by jfrux** [comment]
Sorry, wrong repo!

**Comment by ghedamat** [comment]
@joshuairl easiest option is to not use the commit sha as the revision key and instead use the default `'file-hash'` that varies when files change
