### ISSUE TITLE
Release latest changes to enable storing git commit message

### ISSUE THREAD

**Issue by sohara** [ember-cli-deploy/ember-cli-deploy-revision-data#67]
This commit: https://github.com/ember-cli-deploy/ember-cli-deploy-revision-data/commit/e0eee7673d65dca66bad432c867fa710be159c62 seems very useful, but it is not yet published it seems. Would it be possible to publish a minor or patch version with those changes?

**Comment by lukemelia** [comment]
Released as https://github.com/ember-cli-deploy/ember-cli-deploy-revision-data/releases/tag/v2.0.0-beta.0

Barring any issues, this will become 2.0.0
