### ISSUE TITLE
Doesn't work with Ember 3

### ISSUE THREAD

**Issue by BryanCrotaz** [ember-cli-deploy/ember-cli-deploy-revision-data#70]
After installation, all ember commands respond with 
```
Cannot find module 'ember-cli/lib/ext/promise'
```

**Comment by BryanCrotaz** [comment]
Sorry, wrong library - should have reported in `ember-cli-deploy-revision-key`

**Comment by BryanCrotaz** [comment]
odd - `ember-cli-deploy-revision-key` on npm appears to point to here.

**Comment by achambers** [comment]
I think you’re referring to ecd-revision-data. 

I updated it yesterday. Although you might be experiencing this if the ember-cli-deploy-lightning-pack needs updating which might be the case.
