### ISSUE TITLE
Needs upgraded simple-git. Current version has security vulnerability.

### ISSUE THREAD

**Issue by Skwai** [ember-cli-deploy/ember-cli-deploy-revision-data#87]
https://github.com/advisories/GHSA-3f95-r44v-8mrg

**Comment by ghost** [comment]
Waiting for this too. Dependabot made a PR for it already --> #86. Just need someone to merge it.

**Comment by lukemelia** [comment]
Closed by #86

**Comment by lukemelia** [comment]
Released in https://github.com/ember-cli-deploy/ember-cli-deploy-revision-data/releases/tag/v2.0.0
